### ISSUE TITLE
Fetching video information from Odysee

### ISSUE THREAD

**Issue by onlyjob** [ecency/vision-next#219]
When a link to the video from [Odysee](https://odysee.com) is posted, it would be nice to fetch video information and embed the video similar to how YouTube links are handled. Thanks.

**Comment by feruzm** [comment]
Please share post examples for devs to quickly check. Thank you!

**Comment by onlyjob** [comment]
Well, unlike any YouTube or Bitchute video URL that becomes embedded video (when posted on Ecency), Odysee video URLs (such as https://odysee.com/@onlyjob:f/how_plandemic_is_going_to_end:0) remain just links that can be played only when followed/opened.

Here is one example where I had to accompany Odysee video URL with HTML code (`iframe`) for embedding the video into my post: https://ecency.com/whatsherface/@onlyjob/dyfevtvxmb

**Comment by onlyjob** [comment]
As I've just noticed, instead of fixing this issue, Ecency made it worse because now it removes `iframe` from new posts as "unsupported" so I can't embed a video from Odyssee any more. Not cool... :(

https://ecency.com/whatsherface/@onlyjob/youtube-hates-me-2025-03

**Comment by feruzm** [comment]
@onlyjob we haven't changed how we render odysee links, we have strict rules and follow same code. Only apparently odysee changed their embedding link style. We will have to update our code to include new embedding style they introduced.

**Comment by onlyjob** [comment]
On second thought, I think it is a bug in Youtube embedding: you probably use regex to prohibit youtube iframes, and that particular Odysee video have "YouTube" in its URL [^1] which probably got it removed as "unsupported".

[^1]: https://odysee.com/@whatsherface:2/YouTube-HATES-me!:0

**Comment by onlyjob** [comment]
> ...we haven't changed how we render odysee links, ...

Something definitely changed as another IFRAME to Odysee video was composed as "Unsupported": https://ecency.com/hive-160545/@onlyjob/everyone-still-has-aids-2025

Could you do something about that please?

**Comment by feruzm** [comment]
@onlyjob please check odysee video embeds should be working by now.

**Comment by onlyjob** [comment]
I can see that embedded Odysee video now works in *preview yet published post still shows "Unsupported" instead of a video. (Now preview disagrees with final post.)

https://ecency.com/hive-160545/@onlyjob/battle-of-the-sexes-2025

**Comment by feruzm** [comment]
@onlyjob Thanks, we will double check this... 
@dkildar I think, renderer breaking render-helper parsing, let's check this.
